server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka-server
          uri: https://github.com/LuisEnriqueNavarroGuzman/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-server